from __future__ import annotations

import json
import re
import shutil
import zipfile
from collections import defaultdict
from pathlib import Path

from mc_han.csv_store import read_extracted_csv
from mc_han.extractors.jar import classify_jar_entry
from mc_han.models import ExtractedText
from mc_han.utils.encoding import decode_text
from mc_han.utils.safe_paths import (
    parse_untrusted_relative_path,
    resolve_path_for_operation,
)
from mc_han.utils.safe_zip import (
    BAD_ZIP,
    DEFAULT_ZIP_LIMITS,
    READ_ERROR,
    SafeZipReader,
    ZipSafetyError,
    ZipSafetyLimits,
)

JAR_JSON_SOURCES = {"jar_patchouli", "jar_modonomicon"}
JAR_MARKDOWN_SOURCES = {"jar_ae2guide", "jar_guides"}
LANG_JSON_SOURCES = {"jar_lang", "kubejs_lang", "resourcepack_lang", "lang_name"}
FTB_SOURCES = {"ftbquests_snbt", "ftbquests_lang"}
JAR_CONTAINER_SOURCES = JAR_JSON_SOURCES | JAR_MARKDOWN_SOURCES | {"jar_lang"}
MODPACK_CONTAINER_SOURCES = FTB_SOURCES | {"kubejs_lang", "resourcepack_lang", "lang_name"}


def default_build_dir(modpack_dir: Path) -> Path:
    return Path(modpack_dir) / "mc-han-build"


def default_resourcepack_dir(output_dir: Path) -> Path:
    return Path(output_dir) / "resourcepacks" / "mc-han-cn"


def build_client_resourcepack(*, modpack_dir: Path, csv_path: Path, output_dir: Path) -> dict[str, int]:
    client_root = Path(output_dir) / "mc-han-client-resourcepack"
    stats = build_outputs(
        modpack_dir=modpack_dir,
        csv_path=csv_path,
        output_dir=output_dir,
        resourcepack_dir=client_root,
        include_config=False,
    )
    write_text(
        client_root / "README_CLIENT.txt",
        "Client resource pack generated by mc-han.\n"
        "Copy this folder into the Minecraft resourcepacks directory, then enable it in game.\n",
    )
    return stats


def build_server_pack(*, modpack_dir: Path, csv_path: Path, output_dir: Path) -> dict[str, int]:
    server_root = Path(output_dir) / "mc-han-server-pack"
    stats = build_outputs(
        modpack_dir=modpack_dir,
        csv_path=csv_path,
        output_dir=output_dir,
        config_dir=server_root,
        include_resourcepack=False,
    )
    write_text(
        server_root / "README_SERVER.txt",
        "Server config overlay generated by mc-han.\n"
        "Back up your server first, then copy the config directory into the server modpack.\n"
        "For Windows/PCL2 hosted servers, consider JVM arg: -Dfile.encoding=UTF-8\n",
    )
    return stats


def build_complete_install_package(*, output_dir: Path, translate_names: bool = False) -> Path:
    output_dir = Path(output_dir)
    complete_root = output_dir / "mc-han-complete-install"
    complete_root.mkdir(parents=True, exist_ok=True)
    for name in ("config", "resourcepacks"):
        src = output_dir / name
        dst = complete_root / name
        if dst.exists():
            shutil.rmtree(dst)
        if src.exists():
            shutil.copytree(src, dst)
    bat = "\r\n".join(
        [
            "@echo off",
            "setlocal",
            "echo mc-han complete install helper",
            "echo Copy the config and resourcepacks folders into your modpack directory.",
            "echo Read README_ALL.txt before installing.",
            "pause",
            "",
        ]
    )
    (complete_root / "install_cn_pack.bat").write_text(bat, encoding="ascii", newline="")
    write_text(
        complete_root / "README_ALL.txt",
        (
            "mc-han 完整安装包说明\n\n"
            "1. 安装前请先备份整合包。\n"
            "2. 客户端需要启用 resourcepacks/mc-han-cn 资源包。\n"
            "3. 开服端需要安装 config 覆盖内容。\n"
            "4. PCL2 开局域网或 FRP 穿透时，开服玩家也相当于服务器。\n"
            "5. Windows/PCL2 开服端建议添加 JVM 参数：-Dfile.encoding=UTF-8\n"
        )
        + (name_translation_install_note() if translate_names else ""),
    )
    return complete_root


def build_outputs(
    *,
    modpack_dir: Path,
    csv_path: Path,
    output_dir: Path,
    resourcepack_dir: Path | None = None,
    config_dir: Path | None = None,
    include_resourcepack: bool = True,
    include_config: bool = True,
    zip_limits: ZipSafetyLimits = DEFAULT_ZIP_LIMITS,
) -> dict[str, int]:
    modpack_dir = Path(modpack_dir)
    output_dir = Path(output_dir)
    rows = [row for row in read_extracted_csv(csv_path) if row.translation.strip()]
    grouped: dict[tuple[str, str, str], list[ExtractedText]] = defaultdict(list)
    for row in rows:
        grouped[(row.source_type, row.container, row.file_path)].append(row)

    pack_root = Path(resourcepack_dir) if resourcepack_dir else default_resourcepack_dir(output_dir)
    config_root = Path(config_dir) if config_dir else output_dir
    prevalidate_build_groups(
        modpack_dir=modpack_dir,
        pack_root=pack_root,
        config_root=config_root,
        grouped=grouped,
        include_resourcepack=include_resourcepack,
        include_config=include_config,
    )

    stats = {
        "resource_files": 0,
        "config_files": 0,
        "translated_rows": len(rows),
        "name_rows": sum(1 for row in rows if row.source_type == "lang_name"),
    }
    if include_resourcepack:
        write_pack_mcmeta(pack_root)
    lang_outputs: dict[Path, dict[str, str]] = defaultdict(dict)

    for (source_type, container, file_path), group in sorted(grouped.items()):
        if source_type in LANG_JSON_SOURCES and include_resourcepack:
            relative_output = to_assets_resourcepack_path(file_path)
            for row in group:
                lang_outputs[relative_output][row.key_path] = row.translation
        elif source_type in JAR_JSON_SOURCES and include_resourcepack:
            text = read_container_file(
                modpack_dir,
                container,
                file_path,
                zip_limits=zip_limits,
            )
            data = json.loads(text)
            for row in group:
                set_json_path(data, row.key_path, row.translation)
            relative_output = to_resourcepack_path(file_path, source_type=source_type)
            write_text_within_root(
                pack_root,
                relative_output.as_posix(),
                json.dumps(data, ensure_ascii=False, indent=2) + "\n",
                label=f"resource-pack output for {file_path!r}",
                allowed_top_levels={"assets"},
            )
            stats["resource_files"] += 1
        elif source_type in JAR_MARKDOWN_SOURCES and include_resourcepack:
            text = read_container_file(
                modpack_dir,
                container,
                file_path,
                zip_limits=zip_limits,
            )
            relative_output = to_resourcepack_path(file_path, source_type=source_type)
            write_text_within_root(
                pack_root,
                relative_output.as_posix(),
                replace_exact_segments(text, group),
                label=f"resource-pack output for {file_path!r}",
                allowed_top_levels={"assets"},
            )
            stats["resource_files"] += 1
        elif source_type in FTB_SOURCES and include_config:
            text = read_container_file(modpack_dir, container, file_path)
            relative_output = to_config_overlay_path(file_path)
            write_text_within_root(
                config_root,
                relative_output.as_posix(),
                replace_exact_segments(text, group),
                label=f"config output for {file_path!r}",
                allowed_top_levels={"config"},
            )
            stats["config_files"] += 1

    for relative_output, translations in sorted(lang_outputs.items(), key=lambda item: item[0].as_posix()):
        write_text_within_root(
            pack_root,
            relative_output.as_posix(),
            json.dumps(dict(sorted(translations.items())), ensure_ascii=False, indent=2) + "\n",
            label=f"resource-pack output {relative_output.as_posix()!r}",
            allowed_top_levels={"assets"},
        )
        stats["resource_files"] += 1

    write_build_report(output_dir, stats)
    return stats


def prevalidate_build_groups(
    *,
    modpack_dir: Path,
    pack_root: Path,
    config_root: Path,
    grouped: dict[tuple[str, str, str], list[ExtractedText]],
    include_resourcepack: bool,
    include_config: bool,
) -> None:
    for source_type, container, file_path in sorted(grouped):
        is_resource_group = source_type in LANG_JSON_SOURCES | JAR_JSON_SOURCES | JAR_MARKDOWN_SOURCES
        is_config_group = source_type in FTB_SOURCES
        if not ((include_resourcepack and is_resource_group) or (include_config and is_config_group)):
            continue

        validate_csv_container(modpack_dir, source_type=source_type, container=container)
        if source_type in LANG_JSON_SOURCES:
            if container == "modpack":
                source_top_levels = (
                    {"kubejs"}
                    if source_type == "kubejs_lang"
                    else {"resourcepacks"}
                    if source_type == "resourcepack_lang"
                    else {"kubejs", "resourcepacks"}
                )
                resolve_path_for_operation(
                    modpack_dir,
                    file_path,
                    label="modpack language source path",
                    allowed_top_levels=source_top_levels,
                )
            else:
                parse_untrusted_relative_path(file_path, label="JAR entry")
            relative_output = to_assets_resourcepack_path(file_path)
            resolve_path_for_operation(
                pack_root,
                relative_output.as_posix(),
                label=f"resource-pack output for {file_path!r}",
                allowed_top_levels={"assets"},
            )
        elif source_type in JAR_JSON_SOURCES | JAR_MARKDOWN_SOURCES:
            parse_untrusted_relative_path(file_path, label="JAR entry")
            relative_output = to_resourcepack_path(file_path, source_type=source_type)
            resolve_path_for_operation(
                pack_root,
                relative_output.as_posix(),
                label=f"resource-pack output for {file_path!r}",
                allowed_top_levels={"assets"},
            )
        elif source_type in FTB_SOURCES:
            resolve_path_for_operation(
                modpack_dir,
                file_path,
                label="modpack source path",
                allowed_top_levels={"config"},
            )
            relative_output = to_config_overlay_path(file_path)
            resolve_path_for_operation(
                config_root,
                relative_output.as_posix(),
                label=f"config output for {file_path!r}",
                allowed_top_levels={"config"},
            )


def validate_csv_container(modpack_dir: Path, *, source_type: str, container: str) -> None:
    if container == "modpack":
        if source_type not in MODPACK_CONTAINER_SOURCES:
            raise ValueError(f"{source_type} must use a JAR container under mods")
        return
    if source_type not in JAR_CONTAINER_SOURCES | {"lang_name"}:
        raise ValueError(f"{source_type} must use the modpack container")
    jar_path = resolve_path_for_operation(
        modpack_dir,
        container,
        label="CSV JAR container",
        allowed_top_levels={"mods"},
    )
    if jar_path.suffix.lower() != ".jar":
        raise ValueError("CSV JAR container must be a .jar path under mods")


def read_container_file(
    modpack_dir: Path,
    container: str,
    file_path: str,
    *,
    zip_limits: ZipSafetyLimits = DEFAULT_ZIP_LIMITS,
) -> str:
    if container == "modpack":
        source_path = resolve_path_for_operation(modpack_dir, file_path, label="modpack source path")
        return decode_text(source_path.read_bytes())
    jar_path = resolve_path_for_operation(
        modpack_dir,
        container,
        label="JAR container path",
        allowed_top_levels={"mods"},
    )
    jar_entry = parse_untrusted_relative_path(file_path, label="JAR entry")
    entry_name = jar_entry.as_posix()
    try:
        with zipfile.ZipFile(jar_path) as jar:
            reader: SafeZipReader[str] = SafeZipReader(jar, limits=zip_limits)
            candidates = reader.prepare_candidates(classify_jar_entry)
            if reader.stopped and reader.diagnostics:
                diagnostic = reader.diagnostics[-1]
                raise RuntimeError(
                    f"JAR safety preflight stopped [{diagnostic.code}]: "
                    f"{diagnostic.reason}"
                )
            selected = next((info for info, _source_type in candidates if info.filename == entry_name), None)
            if selected is None:
                matching_diagnostic = next(
                    (item for item in reader.diagnostics if item.entry == entry_name),
                    None,
                )
                if matching_diagnostic is not None:
                    raise RuntimeError(
                        f"Unsafe JAR entry refused [{matching_diagnostic.code}]: "
                        f"{entry_name}: {matching_diagnostic.reason}"
                    )
                raise RuntimeError(f"Supported JAR entry not found: {entry_name}")
            try:
                return decode_text(reader.read_entry(selected))
            except ZipSafetyError as error:
                diagnostic = error.diagnostic
                raise RuntimeError(
                    f"Unsafe JAR entry refused [{diagnostic.code}]: "
                    f"{entry_name}: {diagnostic.reason}"
                ) from error
    except (zipfile.BadZipFile, zipfile.LargeZipFile) as error:
        raise RuntimeError(f"Cannot read JAR [{BAD_ZIP}]: {container}") from error
    except OSError as error:
        raise RuntimeError(
            f"Cannot read JAR [{READ_ERROR}]: {container}: {type(error).__name__}"
        ) from error


def to_resourcepack_path(file_path: str, *, source_type: str | None = None) -> Path:
    source = parse_untrusted_relative_path(file_path, label="resource-pack source path")
    parts = list(source.parts)
    if source_type in JAR_JSON_SOURCES:
        marker = "patchouli_books" if source_type == "jar_patchouli" else "modonomicon"
        try:
            marker_index = [part.lower() for part in parts].index(marker)
        except ValueError:
            marker_index = -1
        for index in range(marker_index + 1, len(parts) - 1):
            if marker_index >= 0 and parts[index].lower() == "en_us":
                parts[index] = "zh_cn"
    return Path(*parts)


def to_assets_resourcepack_path(file_path: str) -> Path:
    source = parse_untrusted_relative_path(file_path, label="language source path")
    try:
        assets_index = next(index for index, part in enumerate(source.parts) if part.lower() == "assets")
    except StopIteration as error:
        raise ValueError(f"Language source path does not contain an assets directory: {file_path!r}") from error
    parts = ["assets", *source.parts[assets_index + 1 :]]
    if len(parts) >= 3 and parts[-2].lower() == "lang" and parts[-1].lower() == "en_us.json":
        parts[-1] = "zh_cn.json"
    return Path(*parts)


def to_config_overlay_path(file_path: str) -> Path:
    source = parse_untrusted_relative_path(file_path, label="config source path")
    parts = list(source.parts)
    for index, part in enumerate(parts):
        if index > 0 and parts[index - 1] == "lang" and part == "en_us":
            parts[index] = "zh_cn"
        elif index > 0 and parts[index - 1] == "lang" and part.startswith("en_us."):
            parts[index] = "zh_cn." + part[len("en_us.") :]
    return Path(*parts)


def write_pack_mcmeta(pack_root: Path) -> None:
    content = {
        "pack": {
            "pack_format": 15,
            "description": "mc-han generated Simplified Chinese localization pack",
        }
    }
    write_text_within_root(
        pack_root,
        "pack.mcmeta",
        json.dumps(content, ensure_ascii=False, indent=2) + "\n",
        label="resource-pack metadata",
    )


def replace_exact_segments(content: str, rows: list[ExtractedText]) -> str:
    updated = content
    for row in sorted(rows, key=lambda item: len(item.original), reverse=True):
        if row.original not in updated:
            continue
        updated = updated.replace(row.original, row.translation, 1)
    return updated


def set_json_path(data: object, key_path: str, value: str) -> None:
    current = data
    tokens = parse_key_path(key_path)
    for token in tokens[:-1]:
        current = current[token] if isinstance(token, int) else current[token]  # type: ignore[index]
    leaf = tokens[-1]
    if isinstance(leaf, int):
        current[leaf] = value  # type: ignore[index]
    else:
        current[leaf] = value  # type: ignore[index]


def parse_key_path(key_path: str) -> list[str | int]:
    tokens: list[str | int] = []
    for part in key_path.split("."):
        if not part:
            continue
        head_match = re.match(r"^[^\[]+", part)
        if head_match:
            tokens.append(head_match.group(0))
        for index in re.findall(r"\[(\d+)\]", part):
            tokens.append(int(index))
    return tokens


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def write_text_within_root(
    root: Path,
    relative_path: str,
    content: str,
    *,
    label: str,
    allowed_top_levels: set[str] | None = None,
) -> Path:
    target = resolve_path_for_operation(
        root,
        relative_path,
        label=label,
        allowed_top_levels=allowed_top_levels,
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    target = resolve_path_for_operation(
        root,
        relative_path,
        label=label,
        allowed_top_levels=allowed_top_levels,
    )
    target.write_text(content, encoding="utf-8", newline="\n")
    return target


def write_build_report(output_dir: Path, stats: dict[str, int]) -> None:
    lines = [
        "mc-han build report",
        f"translated_rows: {stats['translated_rows']}",
        f"resource_files: {stats['resource_files']}",
        f"config_files: {stats['config_files']}",
        "",
        "Install notes:",
        "  Copy resourcepacks/mc-han-cn into the client resourcepacks folder.",
        "  Copy config overlays only after backing up the original config directory.",
        "  Multiplayer servers need the config overlay on the server and the resource pack on clients.",
    ]
    if stats.get("name_rows", 0):
        lines.extend(
            [
                "",
                "Name translation notes:",
                "  This pack translates item/block/entity names and keeps English originals.",
                "  Example: 工程师万用表 (Engineer’s Multimeter)",
                "  Multiplayer players should use the same client resource pack to see matching names.",
            ]
        )
    write_text(Path(output_dir) / "build_report.txt", "\n".join(lines) + "\n")


def name_translation_install_note() -> str:
    return (
        "\n"
        "本汉化包启用了物品/方块名称翻译，并保留英文原名。\n"
        "显示格式示例：\n"
        "工程师万用表 (Engineer’s Multimeter)\n\n"
        "多人联机时，建议所有玩家都安装同一个客户端资源包，否则不同玩家看到的物品名称可能不一致。"
        "注意：物品/方块/实体名称不能只翻译成中文，必须保留英文原名。"
        "格式固定为：中文名 (English Original)。这是硬性要求。\n"
    )
