from __future__ import annotations

import json
import re
import shutil
import zipfile
from collections import defaultdict
from pathlib import Path

from mc_han.csv_store import read_extracted_csv
from mc_han.models import ExtractedText
from mc_han.utils.encoding import decode_text

JAR_JSON_SOURCES = {"jar_patchouli", "jar_modonomicon"}
JAR_MARKDOWN_SOURCES = {"jar_ae2guide", "jar_guides"}
LANG_JSON_SOURCES = {"jar_lang", "kubejs_lang", "resourcepack_lang", "lang_name"}
FTB_SOURCES = {"ftbquests_snbt", "ftbquests_lang"}


def default_build_dir(modpack_dir: Path) -> Path:
    return Path(modpack_dir) / "mc-han-build"


def default_resourcepack_dir(output_dir: Path) -> Path:
    return Path(output_dir) / "resourcepacks" / "mc-han-cn"


def build_client_resourcepack(*, modpack_dir: Path, csv_path: Path, output_dir: Path) -> dict[str, int]:
    client_root = Path(output_dir) / "mc-han-client-resourcepack"
    stats = build_outputs(
        modpack_dir=modpack_dir,
        csv_path=csv_path,
        output_dir=output_dir,
        resourcepack_dir=client_root,
        include_config=False,
    )
    write_text(
        client_root / "README_CLIENT.txt",
        "Client resource pack generated by mc-han.\n"
        "Copy this folder into the Minecraft resourcepacks directory, then enable it in game.\n",
    )
    return stats


def build_server_pack(*, modpack_dir: Path, csv_path: Path, output_dir: Path) -> dict[str, int]:
    server_root = Path(output_dir) / "mc-han-server-pack"
    stats = build_outputs(
        modpack_dir=modpack_dir,
        csv_path=csv_path,
        output_dir=output_dir,
        config_dir=server_root,
        include_resourcepack=False,
    )
    write_text(
        server_root / "README_SERVER.txt",
        "Server config overlay generated by mc-han.\n"
        "Back up your server first, then copy the config directory into the server modpack.\n"
        "For Windows/PCL2 hosted servers, consider JVM arg: -Dfile.encoding=UTF-8\n",
    )
    return stats


def build_complete_install_package(*, output_dir: Path, translate_names: bool = False) -> Path:
    output_dir = Path(output_dir)
    complete_root = output_dir / "mc-han-complete-install"
    complete_root.mkdir(parents=True, exist_ok=True)
    for name in ("config", "resourcepacks"):
        src = output_dir / name
        dst = complete_root / name
        if dst.exists():
            shutil.rmtree(dst)
        if src.exists():
            shutil.copytree(src, dst)
    bat = "\r\n".join(
        [
            "@echo off",
            "setlocal",
            "echo mc-han complete install helper",
            "echo Copy the config and resourcepacks folders into your modpack directory.",
            "echo Read README_ALL.txt before installing.",
            "pause",
            "",
        ]
    )
    (complete_root / "install_cn_pack.bat").write_text(bat, encoding="ascii", newline="")
    write_text(
        complete_root / "README_ALL.txt",
        (
            "mc-han 完整安装包说明\n\n"
            "1. 安装前请先备份整合包。\n"
            "2. 客户端需要启用 resourcepacks/mc-han-cn 资源包。\n"
            "3. 开服端需要安装 config 覆盖内容。\n"
            "4. PCL2 开局域网或 FRP 穿透时，开服玩家也相当于服务器。\n"
            "5. Windows/PCL2 开服端建议添加 JVM 参数：-Dfile.encoding=UTF-8\n"
        )
        + (name_translation_install_note() if translate_names else ""),
    )
    return complete_root


def build_outputs(
    *,
    modpack_dir: Path,
    csv_path: Path,
    output_dir: Path,
    resourcepack_dir: Path | None = None,
    config_dir: Path | None = None,
    include_resourcepack: bool = True,
    include_config: bool = True,
) -> dict[str, int]:
    modpack_dir = Path(modpack_dir)
    output_dir = Path(output_dir)
    rows = [row for row in read_extracted_csv(csv_path) if row.translation.strip()]
    grouped: dict[tuple[str, str, str], list[ExtractedText]] = defaultdict(list)
    for row in rows:
        grouped[(row.source_type, row.container, row.file_path)].append(row)

    stats = {
        "resource_files": 0,
        "config_files": 0,
        "translated_rows": len(rows),
        "name_rows": sum(1 for row in rows if row.source_type == "lang_name"),
    }
    pack_root = Path(resourcepack_dir) if resourcepack_dir else default_resourcepack_dir(output_dir)
    config_root = Path(config_dir) if config_dir else output_dir
    if include_resourcepack:
        write_pack_mcmeta(pack_root)
    lang_outputs: dict[Path, dict[str, str]] = defaultdict(dict)

    for (source_type, container, file_path), group in sorted(grouped.items()):
        if source_type in LANG_JSON_SOURCES and include_resourcepack:
            output_path = pack_root / to_assets_resourcepack_path(file_path)
            for row in group:
                lang_outputs[output_path][row.key_path] = row.translation
        elif source_type in JAR_JSON_SOURCES and include_resourcepack:
            text = read_container_file(modpack_dir, container, file_path)
            data = json.loads(text)
            for row in group:
                set_json_path(data, row.key_path, row.translation)
            output_path = pack_root / to_resourcepack_path(file_path)
            write_text(output_path, json.dumps(data, ensure_ascii=False, indent=2) + "\n")
            stats["resource_files"] += 1
        elif source_type in JAR_MARKDOWN_SOURCES and include_resourcepack:
            text = read_container_file(modpack_dir, container, file_path)
            output_path = pack_root / to_resourcepack_path(file_path)
            write_text(output_path, replace_exact_segments(text, group))
            stats["resource_files"] += 1
        elif source_type in FTB_SOURCES and include_config:
            text = read_container_file(modpack_dir, container, file_path)
            output_path = config_root / to_config_overlay_path(file_path)
            write_text(output_path, replace_exact_segments(text, group))
            stats["config_files"] += 1

    for output_path, translations in sorted(lang_outputs.items(), key=lambda item: item[0].as_posix()):
        write_text(output_path, json.dumps(dict(sorted(translations.items())), ensure_ascii=False, indent=2) + "\n")
        stats["resource_files"] += 1

    write_build_report(output_dir, stats)
    return stats


def read_container_file(modpack_dir: Path, container: str, file_path: str) -> str:
    if container == "modpack":
        return decode_text((modpack_dir / file_path).read_bytes())
    with zipfile.ZipFile(modpack_dir / container) as jar:
        return decode_text(jar.read(file_path))


def to_resourcepack_path(file_path: str) -> Path:
    normalized = file_path.replace("\\", "/")
    normalized = normalized.replace("/en_us/", "/zh_cn/")
    return Path(*normalized.split("/"))


def to_assets_resourcepack_path(file_path: str) -> Path:
    normalized = file_path.replace("\\", "/")
    marker = "/assets/"
    if normalized.startswith("assets/"):
        assets_path = normalized
    elif marker in normalized:
        assets_path = normalized.split(marker, 1)[1]
        assets_path = "assets/" + assets_path
    else:
        assets_path = normalized
    assets_path = assets_path.replace("/lang/en_us.json", "/lang/zh_cn.json")
    return Path(*assets_path.split("/"))


def to_config_overlay_path(file_path: str) -> Path:
    normalized = file_path.replace("\\", "/")
    normalized = normalized.replace("/lang/en_us.", "/lang/zh_cn.")
    normalized = normalized.replace("/lang/en_us/", "/lang/zh_cn/")
    return Path(*normalized.split("/"))


def write_pack_mcmeta(pack_root: Path) -> None:
    pack_root.mkdir(parents=True, exist_ok=True)
    content = {
        "pack": {
            "pack_format": 15,
            "description": "mc-han generated Simplified Chinese localization pack",
        }
    }
    write_text(pack_root / "pack.mcmeta", json.dumps(content, ensure_ascii=False, indent=2) + "\n")


def replace_exact_segments(content: str, rows: list[ExtractedText]) -> str:
    updated = content
    for row in sorted(rows, key=lambda item: len(item.original), reverse=True):
        if row.original not in updated:
            continue
        updated = updated.replace(row.original, row.translation, 1)
    return updated


def set_json_path(data: object, key_path: str, value: str) -> None:
    current = data
    tokens = parse_key_path(key_path)
    for token in tokens[:-1]:
        current = current[token] if isinstance(token, int) else current[token]  # type: ignore[index]
    leaf = tokens[-1]
    if isinstance(leaf, int):
        current[leaf] = value  # type: ignore[index]
    else:
        current[leaf] = value  # type: ignore[index]


def parse_key_path(key_path: str) -> list[str | int]:
    tokens: list[str | int] = []
    for part in key_path.split("."):
        if not part:
            continue
        head_match = re.match(r"^[^\[]+", part)
        if head_match:
            tokens.append(head_match.group(0))
        for index in re.findall(r"\[(\d+)\]", part):
            tokens.append(int(index))
    return tokens


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def write_build_report(output_dir: Path, stats: dict[str, int]) -> None:
    lines = [
        "mc-han build report",
        f"translated_rows: {stats['translated_rows']}",
        f"resource_files: {stats['resource_files']}",
        f"config_files: {stats['config_files']}",
        "",
        "Install notes:",
        "  Copy resourcepacks/mc-han-cn into the client resourcepacks folder.",
        "  Copy config overlays only after backing up the original config directory.",
        "  Multiplayer servers need the config overlay on the server and the resource pack on clients.",
    ]
    if stats.get("name_rows", 0):
        lines.extend(
            [
                "",
                "Name translation notes:",
                "  This pack translates item/block/entity names and keeps English originals.",
                "  Example: 工程师万用表 (Engineer’s Multimeter)",
                "  Multiplayer players should use the same client resource pack to see matching names.",
            ]
        )
    write_text(Path(output_dir) / "build_report.txt", "\n".join(lines) + "\n")


def name_translation_install_note() -> str:
    return (
        "\n"
        "本汉化包启用了物品/方块名称翻译，并保留英文原名。\n"
        "显示格式示例：\n"
        "工程师万用表 (Engineer’s Multimeter)\n\n"
        "多人联机时，建议所有玩家都安装同一个客户端资源包，否则不同玩家看到的物品名称可能不一致。"
        "注意：物品/方块/实体名称不能只翻译成中文，必须保留英文原名。"
        "格式固定为：中文名 (English Original)。这是硬性要求。\n"
    )
